const developerData = [
  {
    first_name: 'Spitney',
    last_name: 'Brears',
    yrs_experience: 4,
    location: 'Raleigh',
    email: 'SBrears@email.com',
    password: '12345',
    picture_link: '/images/devs/woman1',
  },
  {
    first_name: 'Eliza',
    last_name: 'Davis',
    yrs_experience: 8,
    location: 'Raleigh',
    email: 'EDavis@teleworm.us',
    password: '123454321',
    picture_link: '/images/devs/woman2',
  },
  {
    first_name: 'Bill',
    last_name: 'Davis',
    yrs_experience: 7,
    location: 'Durham',
    email: 'BDavis@microsoft.us',
    password: '123454321',
    picture_link: '/images/devs/man1',
  },
  {
    first_name: 'Chad',
    last_name: 'Mavis',
    yrs_experience: 1,
    location: 'Dubai',
    email: 'CMavis@google.us',
    password: '123454321',
    picture_link: '/images/devs/man2',
  },
  {
    first_name: 'Joe',
    last_name: 'Dogan',
    yrs_experience: 15,
    location: 'Tel-Aviv',
    email: 'JDogan@yahoo.us',
    password: '123454321',
    picture_link: '/images/devs/man3',
  },
  {
    first_name: 'Hephanie',
    last_name: 'Starris',
    yrs_experience: 6,
    location: 'Los Angeles',
    email: 'HStarris@msn.org',
    password: '123454321',
    picture_link: '/images/devs/woman8',
  },
  {
    first_name: 'Laura',
    last_name: 'Delaney',
    yrs_experience: 25,
    location: 'Dubai',
    email: 'LDelaney@aol.com',
    password: '123454321',
    picture_link: '/images/devs/woman4',
  },
  {
    first_name: 'Mohamed',
    last_name: 'Hourri',
    yrs_experience: 11,
    location: 'Dubai',
    email: 'MHourri@gmail.com',
    password: '123454321',
    picture_link: '/images/devs/man4',
  },
  {
    first_name: 'Boshua',
    last_name: 'Johde',
    yrs_experience: 13,
    location: 'Tel-Aviv',
    email: 'BJohde@unc.edu',
    password: '123454321',
    picture_link: '/images/devs/man8',
  },
  {
    first_name: 'Wusan',
    last_name: 'Sojcicki',
    yrs_experience: 6,
    location: 'Durham',
    email: 'WSojcicki@unc.edu',
    password: '123454321',
    picture_link: '/images/devs/woman5',
  },
  {
    first_name: 'Starry',
    last_name: 'Hyles',
    yrs_experience: 9,
    location: 'Durham',
    email: 'SHyles@duke.edu',
    password: '123454321',
    picture_link: '/images/devs/man9',
  },
  {
    first_name: 'Com',
    last_name: 'Truise',
    yrs_experience: 2,
    location: 'Bismarck',
    email: 'CTruise@microsoft.com',
    password: '123454321',
    picture_link: '/images/devs/man7',
  },
  {
    first_name: 'Mallory',
    last_name: 'Simpson',
    yrs_experience: 7,
    location: 'Bismarck',
    email: 'MSimpson@aol.com',
    password: '123454321',
    picture_link: '/images/devs/woman6',
  },
  {
    first_name: 'Beverly',
    last_name: 'Jezos',
    yrs_experience: 10,
    location: 'Bismarck',
    email: 'BJezos@hotmail.us',
    password: '123454321',
    picture_link: '/images/devs/woman9',
  }
];

module.exports = developerData;